// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using robinhood_mvc.Data;

#nullable disable

namespace robinhood_mvc.Migrations
{
    [DbContext(typeof(RobinhoodContext))]
    [Migration("20220802163410_RobinhoodMigrations")]
    partial class RobinhoodMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("robinhood_mvc.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Semester")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instructor = "Imad Moukadem",
                            Name = "CMPS 278",
                            Rating = 5,
                            Semester = "Summer",
                            Year = "2021-2022"
                        },
                        new
                        {
                            Id = 2,
                            Instructor = "Mahmoud Bdeir",
                            Name = "CMPS 253",
                            Rating = 3,
                            Semester = "Spring",
                            Year = "2021-2022"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
